# Custom Zsh file init
for config (~/.config/zsh/init/*.zsh) source $config

# Source General Environment Variables
source ~/.config/env.sh
set PATH $PATH /Users/will/.local/bin #PipX

# Start Plugins
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"